# Load required MacBook modules on boot

# Camera
facetimehd

# Audio (Cirrus Logic)
snd_hda_macbookpro

# Touch Bar (Built-in on Linux >= 6.15)
hid-appletb-kbd
hid-appletb-bl
appletbdrm

# Bluetooth
btusb
